version: '3.8'
services:
  db:
    image: mysql:8.0.33
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/data

  check-db-started: #Just to be sure that DB is really ready before app starts.
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:3306 -timeout 60s'

  samplebootapp:
    container_name: spring-boot-basic-app-docker
    build:
      dockerfile: Dockerfile
    depends_on:
      check-db-started:
        condition: service_completed_successfully
    image: spring-boot-basic-app-docker:latest
    #environment:
    #  - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - '8081:8081'

volumes:
  db:
    driver: local

