server:
  port: 8081
  error:
    include-message: always

spring:
  datasource: #For local, we are using h2
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa: #For local, we are using h2
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    com.websystique: TRACE
    org.springframework: WARN
