spring:
  application:
    name: Sample SpringBoot App
  error:
    path: /error
    whitelabel:
      enabled: false
    thymeleaf:
      enabled: true
      cache: false
      prefix: classpath:/templates/
      suffix: .html

logging:
  level:
    root: INFO
    com.websystique: INFO
    org.springframework: WARN
