spring:
  application:
    name: Sample SpringBoot App
  datasource: #For higher environments, make sure to set the right details as per your environment
    url: jdbc:mysql://mysql:3306/example_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: #For higher environments, make sure to set the right details as per your environment
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  error:
    path: /error
    whitelabel:
      enabled: false
    thymeleaf:
      enabled: true
      cache: false
      prefix: classpath:/templates/
      suffix: .html

logging:
  level:
    root: INFO
    com.websystique: INFO
    org.springframework: WARN
