
spring:
  application:
    name: spring-boot-basic-app
  jackson:
    deserialization:
      fail-on-unknown-properties: true


logging:
  level:
    root: INFO
    com.websystique: INFO
    org.springframework: WARN
