apiVersion: v1
kind: Service
metadata:
  name: spring-boot-basic-app
spec:
  type: NodePort
  selector:
    app: spring-boot-basic-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007