apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo
  name: role-configmap-reader
rules:
  - apiGroups: [""]
    verbs: ["get", "list", "watch"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]