server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: spring-boot-basic-app
  datasource: #For higher environments, make sure to set the right details as per your environment
    url: jdbc:mysql://db:3306/example_db?createDatabaseIfNotExist=true #db ref from compose
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: #For higher environments, make sure to set the right details as per your environment
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update #Change this to "none" as you should already have the table.
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    com.websystique: INFO
    org.springframework: WARN
