version: '3.8'
services:
  db:
    image: mysql:8.0.33
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/data
volumes:
  db:
    driver: local