# DB is running in container
spring:
  datasource:
    url: jdbc:mysql://db:3306/example_db?createDatabaseIfNotExist=true #db ref from compose
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    com.websystique: TRACE
    org.springframework: WARN
