apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: spring-boot-sample-application
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007